# Policy Iteration Algorithm

1. **Initialization**
    - Initialize policy $\pi$ arbitrarily (e.g., $\pi(s) = \text{argmax}_a \{ R_a(s) \}$ for all $s \in S$)
    - Initialize utility $U(s)$ arbitrarily for all $s \in S$

2. **Policy Evaluation**
    - Repeat until convergence:
        - For each state $s \in S$:
            - $U(s) \leftarrow R_{\pi(s)}(s) + \gamma \sum_{s'} P_{\pi(s)}(s, s') U(s')$

3. **Policy Improvement**
    - For each state $s \in S$:
        - $\pi'(s) \leftarrow \text{argmax}_a \{ R_a(s) + \gamma \sum_{s'} P_a(s, s') U(s') \}$
    - If $\pi' = \pi$, stop and return $\pi$ and $U$
    - Otherwise, set $\pi \leftarrow \pi'$ and go to step 2

# Value Iteration Algorithm

1. **Initialization**
    - Initialize utility $U(s)$ arbitrarily for all $s \in S$

2. **Bellman Optimality Update**
    - Repeat until convergence:
        - For each state $s \in S$:
            - $U(s) \leftarrow \max_a \{ R_a(s) + \gamma \sum_{s'} P_a(s, s') U(s') \}$

3. **Derive Policy from Utility**
    - For each state $s \in S$:
        - $\pi(s) \leftarrow \text{argmax}_a \{ R_a(s) + \gamma \sum_{s'} P_a(s, s') U(s') \}$
    - Return $\pi$ and $U$


**policy evaluation**

In OpenAI Gym, the number of actions available in an environment depends on the type of action space it has. Here's how you can check the number of actions:

- For a **discrete** and one-dimensional action space, you can use the following code to get the number of actions:
```python
import gym
env = gym.make("Acrobot-v1")
a = env.action_space
print(a)                    # prints Discrete(3)
print(a.n)                  # prints 3
```
This will print the number of actions available, which is simply an integer¹.

- If the action space is **multi-dimensional** and discrete, you would use `nvec` to get an array describing the number of available actions for each dimension:
```python
import gym
env = gym.make("YourEnvHere")
print(env.action_space.nvec) # prints array([5, 5, 5, 5], dtype=int64) for a MultiDiscrete space
```
This gives you a numpy array with the number of actions available in each dimension².

- For a **continuous** action space, you would get a `Box` object, and you can access its properties like so:
```python
import gym
env = gym.make("MountainCarContinuous-v0")
a = env.action_space
print(a)                    # prints Box(1,)
print(a.shape)              # prints (1,)
print(a.high)               # prints [1.] for the maximum value
print(a.low)                # prints [-1.] for the minimum value
```
This will give you the shape of the action space and the bounds for each dimension¹.

As for the dates, if you're referring to the release dates or update dates for OpenAI Gym environments, this information isn't provided in the search results. You might want to check the official OpenAI Gym GitHub repository or the release notes for the most accurate and up-to-date information.

Source: Conversation with Copilot, 5/30/2024
(1) How to check the actions available in OpenAI gym environment?. https://stackoverflow.com/questions/62303994/how-to-check-the-actions-available-in-openai-gym-environment.
(2) OpenAI Gym: Walk through all possible actions in an action space. https://stackoverflow.com/questions/64588828/openai-gym-walk-through-all-possible-actions-in-an-action-space.
(3) How to get the number of valid actions for a descrete action space of .... https://github.com/openai/gym/issues/2005.
(4) undefined. https://github.com/openai/multiagent-particle-envs/blob/master/multiagent/environment.py.
To find out the number of states in an OpenAI Gym environment, you can check the `observation_space` attribute. This attribute describes the format of valid observations for the environment. Here's how you can do it:

```python
import gym
env = gym.make("YourEnvNameHere")
print(env.observation_space)
```

For discrete state spaces, this will typically return a `Discrete` object with a single integer indicating the number of possible states. For example, in the Taxi-v2 environment, there are **500 states**³.

For continuous state spaces, you'll get a `Box` object, which represents an n-dimensional box, so you can check the `shape` attribute to find out the size of the state space:

```python
print(env.observation_space.n)
```

This will give you a tuple representing the dimensions of the state space. Keep in mind that for continuous spaces, the number of states is technically infinite, as the states are represented by real numbers within given bounds.

If you're looking for the specific number of states for a particular environment, you might need to refer to the environment's documentation or source code, as this information is not always explicitly stated. For instance, the Taxi-v2 environment has a total of **500 states** as mentioned earlier³.

Source: Conversation with Copilot, 5/30/2024
(1) What are the different states in Open AI Taxi Environment?. https://stats.stackexchange.com/questions/359638/what-are-the-different-states-in-open-ai-taxi-environment.
(2) How to set a openai-gym environment start with a specific state not the .... https://stackoverflow.com/questions/57839665/how-to-set-a-openai-gym-environment-start-with-a-specific-state-not-the-env-res.
(3) Reinforcement Q-Learning from Scratch in Python with OpenAI Gym. https://www.learndatasci.com/tutorials/reinforcement-q-learning-scratch-python-openai-gym/.
(4) Getting Started With OpenAI Gym | Built In. https://builtin.com/software-engineering-perspectives/openai-gym.
(5) How to check the actions available in OpenAI gym environment?. https://stackoverflow.com/questions/62303994/how-to-check-the-actions-available-in-openai-gym-environment.

In [1]:
# Import necessary libraries
import numpy as np
import gym 

# Create the FrozenLake environment
env= gym.make("FrozenLake-v1")

# Get the number of states and actions from the environment
number_states= env.observation_space.n
number_action= env.action_space.n

# Initialize a random policy
random_policy= np.ones((number_states,number_action))/number_action 

# Set the discount factor, the small threshold theta, and the maximum number of iterations
discount_factor =0.99
theta=1e-10
max_iteration=20000

# Print the shape of the random policy
print(random_policy.shape)

# Define the policy evaluation function
def policy_evaluaton(policy=random_policy,gamma=discount_factor,theta=theta,max_iteration=max_iteration ):
    # Initialize the value function
    pre_v =np.zeros(number_states)
    iteration=0
    delta=0
    while True:
        iteration+=1 
        # Initialize the new value function
        V=np.zeros(number_states)
        # For each state
        for state in range(number_states):
            # For each action
            for action in range(number_action):
                # For each possible next state
                for prob, next_state, reward, done in env.P[state][action]:
                    # Update the value function
                    V[state]+= policy[state][action]*prob*(reward+gamma*pre_v[next_state])

        # Calculate the maximum change in value function
        delta=np.max(np.abs(V-pre_v))
        # Update the value function
        pre_v= np.copy(V)

        # If the maximum change in value function is less than the threshold, stop. 
        # Also stop if the number of iterations has reached the maximum limit
        if delta < theta or iteration >= max_iteration :break
    return V,iteration

# Evaluate the policy and print the value function
V,i=policy_evaluaton() 
print(i)
print(V.reshape((4,4)))


(16, 4)
93
[[0.01235614 0.01042446 0.01933844 0.00947775]
 [0.01478705 0.         0.03889445 0.        ]
 [0.03260247 0.08433764 0.13781085 0.        ]
 [0.         0.17034482 0.43357944 0.        ]]


Calculating  Value functions for a deterministic policy

In [2]:
deterministic_policy = np.array([[0, 0, 1, 0],
[1, 0, 0, 0],
[0, 1, 0, 0],
[0, 0, 0, 1],
[1, 0, 0, 0],
[1, 0, 0, 0],
[0, 0, 1, 0],
[1, 0, 0, 0],
[0, 0, 0, 1],
[0, 1, 0, 0],
[0, 0, 0, 1],
[1, 0, 0, 0],
[1, 0, 0, 0],
[0, 0, 1, 0],
[0, 1, 0, 0],
[0, 1, 0, 0]])
V,itera =policy_evaluaton(policy=deterministic_policy)
print(V.reshape((4,4)))
print(f'iterastin:{itera}')

[[0.09554433 0.04705915 0.0470064  0.04562386]
 [0.1469248  0.         0.04976062 0.        ]
 [0.20275753 0.26473443 0.10378337 0.        ]
 [0.         0.49568466 0.74165563 0.        ]]
iterastin:218


In [3]:
def greedy_policy(V=V, gamma=discount_factor):
    # Initialize the policy matrix with zeros
    policy = np.zeros((number_states, number_action))
    
    # Initialize the Q-value matrix with zeros
    Q = np.zeros((number_states, number_action))
    
    # Iterate over all states
    for state in range(number_states):
        # Iterate over all possible actions
        for action in range(number_action):
            # Calculate the Q-value for each state-action pair
            for prob, next_state, reward, done in env.P[state][action]:
                # Update the Q-value based on the transition probabilities, rewards, and discount factor
                Q[state][action] += prob * (reward + gamma * V[next_state])
    
    # Find the index (action) of the max Q-value for each state
    max_index = np.argmax(Q, axis=1)
    
    # Construct the greedy policy based on the max Q-values
    for i, optimal_action in enumerate(max_index):
        # Set the action with the highest Q-value to 1 (indicating it's the chosen action)
        policy[i][optimal_action] = 1
    
    # Return the greedy policy and the Q-value matrix
    return policy, Q


policy, Q=greedy_policy(V,gamma=discount_factor)


In [4]:

# Initialize a random policy
def policy_iteration(policy=random_policy):
    old_policy=policy
    iteration=0
    while True:
        V,_= policy_evaluaton(policy=old_policy)
        new_policy, Q=greedy_policy(V=V, gamma=discount_factor)
        
      
        comparison= (old_policy==new_policy)
        if comparison.all()==True: break
        
        old_policy=new_policy
        iteration+=1
    return new_policy, iteration

random_policy= np.random.rand(number_states,number_action) 
optimal_policy_politer, iteration=policy_iteration()        
print("Optimal Policy:")
print(optimal_policy_politer)

        
        
        


Optimal Policy:
[[1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]]


In [6]:
import time 
def run_policy(env, policy):
    state = env.reset()
    if isinstance(state, tuple):
        state = state[0]  # For newer versions of gym that return a tuple (state, info)
    env.render()
    done = False
    
    while not done:
        # Print the current state for debugging
        print(f"Current state: {state}")
        
        # Ensure the state is an integer index for the policy array
        try:
            action = np.argmax(policy[state])
        except IndexError as e:
            print(f"IndexError: {e}")
            print(f"Policy shape: {policy.shape}, state: {state}")
            break
        
        # Print the chosen action for debugging
        print(f"Chosen action: {action}")
        
        # Take the action in the environment
        step_result = env.step(action)
        if len(step_result) == 4:
            next_state, reward, done, info = step_result
        else:
            next_state, reward, done, truncated, info = step_result
            done = done or truncated
        
        if isinstance(next_state, tuple):
            next_state = next_state[0]  # For newer versions of gym that return a tuple (state, info)
        
        # Render the new state of the environment
        env.render()
        print(f"New state: {next_state}, Reward: {reward}, Done: {done}")
        
        state = next_state

# Create the environment
env = gym.make("FrozenLake-v1", render_mode="human")


# Run the policy on the environment
run_policy(env, optimal_policy_politer)
time.sleep(10)

env.close()



Current state: 0
Chosen action: 0


c:\Users\roozu\anaconda3\Lib\site-packages\gym\utils\passive_env_checker.py:233: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
  if not isinstance(terminated, (bool, np.bool8)):


New state: 0, Reward: 0.0, Done: False
Current state: 0
Chosen action: 0
New state: 4, Reward: 0.0, Done: False
Current state: 4
Chosen action: 0
New state: 8, Reward: 0.0, Done: False
Current state: 8
Chosen action: 3
New state: 8, Reward: 0.0, Done: False
Current state: 8
Chosen action: 3
New state: 4, Reward: 0.0, Done: False
Current state: 4
Chosen action: 0
New state: 0, Reward: 0.0, Done: False
Current state: 0
Chosen action: 0
New state: 0, Reward: 0.0, Done: False
Current state: 0
Chosen action: 0
New state: 4, Reward: 0.0, Done: False
Current state: 4
Chosen action: 0
New state: 0, Reward: 0.0, Done: False
Current state: 0
Chosen action: 0
New state: 4, Reward: 0.0, Done: False
Current state: 4
Chosen action: 0
New state: 8, Reward: 0.0, Done: False
Current state: 8
Chosen action: 3
New state: 4, Reward: 0.0, Done: False
Current state: 4
Chosen action: 0
New state: 0, Reward: 0.0, Done: False
Current state: 0
Chosen action: 0
New state: 0, Reward: 0.0, Done: False
Current stat

**value policy**

In [ ]:
# Import necessary libraries
import numpy as np
import gym 

# Create the FrozenLake environment
env= gym.make("FrozenLake-v1")

# Get the number of states and actions from the environment
number_states= env.observation_space.n
number_action= env.action_space.n
gamma =0.99
theta= 1e-6 #stoping condition 

def value_iterstion():
    policy= np.zeros((number_states,number_action))
    pre_V= np.zeros((number_states,1))
    
    iteration=0
    while True:
        Q= np.zeros((number_states,number_action))
        
        for state in range(number_states):
            for action in range(number_action):
                for prob, next_state, reward, done in env.P[state][action]:
                    # Update the Q-value based on the transition probabilities, rewards, and discount factor
                    Q[state][action] += prob * (reward + gamma * pre_V[next_state])
        V=np.max(Q,axis=1)
        if np.max(np.max(np.abs(pre_V-V))) < theta: 
            break
        pre_V = V.copy()
        iteration += 1
    return V, Q,iteration

V, Q,iteration=value_iterstion()
optimal_policy=np.argmax(Q,axis=1)
print(np.argmax(Q,axis=1))
print(np.argmax(optimal_policy_politer,axis=1))
 

[0 3 3 3 0 0 0 0 3 1 0 0 0 2 1 0]
[0 3 3 3 0 0 0 0 3 1 0 0 0 2 1 0]


C:\Users\roozu\AppData\Local\Temp\ipykernel_13944\320221126.py:26: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  Q[state][action] += prob * (reward + gamma * pre_V[next_state])


In [ ]:
# # make this code more clearer and readable by adding commment

# import numpy as np
# import gym 
# env= gym.make("FrozenLake-v1")
# number_states= env.observation_space.n
# number_action= env.action_space.n
# random_policy= np.ones((number_states,number_action))/number_action 
# discount_factor =1
# theta=0.0001
# max_iteration=20000
# print(random_policy.shape)
# def policy_evaluaton(policy=random_policy,gamma=discount_factor,theta=theta,max_iteration=max_iteration ):
#     pre_v =np.zeros(number_states)
#     i=1  
#     while True:
#         # print("iteation",i)
#         i+=1
#         delta=0
#         V=np.zeros(number_states)
#         for state in range(number_states):
#             # print("current state: ",state)
#             for action in range(number_action):
#                 for prob, next_state, reward, done in env.P[state][action]:
#                     # print(prob, next_state)
#                     V[state]+= policy[state][action]*prob*(reward+gamma*pre_v[next_state])

#         delta=np.max(np.abs(V-pre_v))
#         pre_v= np.copy(V)

#         if delta < theta or i >= max_iteration :break
#     return V,i

# V,i=policy_evaluaton() 
# print(V)      
        

In [ ]:
# import numpy as np
# from tqdm import tqdm

# def policy_evaluation(policy, gamma, number_states, number_actions, env, theta=0.01, max_iterations=200):
#     """
#     Evaluate a policy given an environment and a full description of the environment's dynamics.
    
#     Args:
#         policy: [S, A] shaped matrix representing the policy.
#         gamma: Discount factor.
#         number_states: Number of states in the environment.
#         number_actions: Number of actions in the environment.
#         env: OpenAI env. env.P represents the transition probabilities of the environment.
#         theta: We stop evaluation once our value function change is less than theta for all states.
#         max_iterations: Maximum number of iterations to prevent infinite loops.
    
#     Returns:
#         Vector of length number_states representing the value function.
#     """
#     V = np.zeros(number_states)
#     for i in tqdm(range(max_iterations), desc='Policy Evaluation Progress'):
#         prev_V = np.copy(V)
#         for state in range(number_states):
#             V[state] = sum([policy[state][action] * sum([prob * (reward + gamma * prev_V[next_state])
#                              for prob, next_state, reward, _ in env.P[state][action]])
#                              for action in range(number_actions)])
#         delta = np.max(np.abs(prev_V - V))
#         if delta < theta:
#             print(f'Policy evaluated in {i+1} iterations.')
#             break
#     return V
        
# policy_evaluaton()


In [ ]:
# def policy_evaluaton(policy=random_policy,gamma=discount_factor ):
#     pre_v =np.zeros(number_states)
#     delta=0
#     theta= 0.01
#     i=1  
    
#     while True:
#         print("iteation",i)
#         i+=1
#         for state in range(number_states):
#             # print("current state: ",state)
#             delta=0
#             V=np.zeros(number_states)
#             for action in range(number_action):
#                 for prob, next_state, reward, done in env.P[state][action]:
#                     # print(prob, next_state)
#                     V[state]+= policy[state][action]*prob*(reward+gamma*pre_v[next_state])

#         delta=np.max(np.abs(V-pre_v))
#         pre_v= np.copy(V)
#         print(delta)
#         print(V)
#         print(pre_v)
#         if delta < theta :break
    



#         # error= 0.001    
#         # if delta <= error: break
        
        
# policy_evaluaton()


In [ ]:
        
# Set the discount factor, the small threshold theta, and the maximum number of iterations
# discount_factor =0.99
# theta=1e-2
# max_iteration=2000
# policy_pre=random_policy
# iteration=1
# while True:
#     iteration+=1
#     V_pre,_= policy_evaluaton(policy=policy_pre,gamma=discount_factor,theta=theta,max_iteration=max_iteration )
#     new_policy,_= greedy_policy(V=V_pre, gamma=discount_factor)
#     V_new,_= policy_evaluaton(policy=new_policy,gamma=discount_factor,theta=theta,max_iteration=max_iteration )
#     delta=np.max(np.abs(V_new-V_pre))
#     if delta < theta or iteration >= max_iteration :break